[package]
name = "svg_sprite_parser"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.14.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8.5"
